import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/components/providers/ReduxProviders";

// Configure the Gellix font family
const gellix = localFont({
  src: [
    {
      path: "./fonts/Gellix-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gellix-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Gellix-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-gellix",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gellix.variable} antialiased`}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
